[build-system]
requires = ["setuptools >= 77.0.3","pygame >=2.5.3"]
build-backend = "setuptools.build_meta"
[project]
name = "gpc"
version = "1.0.0"
authors = [
  { name="PhysForm", github="https://github.com/PhysForm" },
]
description = "The PythonExtra gint Module Emulator for PC"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GNU GPL"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/PhysForm/gpc"
Issues = "https://github.com/PhysForm/gpc/issues"
